### ISSUE TITLE
Retrieve data of day/night meter (2 counters)

### ISSUE THREAD

**Issue by Sheugel** [junalmeida/homeassistant-addons#22]
Hi,
Thanks for the great addon. I tested it successfully with my gas meter.
I have a day/night meter for electricty with two counters one under the other.
Would it be possible to retrieve the data from both these counters?
Thanks!

**Comment by junalmeida** [comment]
I'm afraid with the current version you would need a second camera to do that.

**Comment by Sheugel** [comment]
Thanks, with the help of the camera proxy integrationwithin Home Asssitant [https://www.home-assistant.io/integrations/proxy/](url) I'm able to crop the zone of the counter.
Problem is the necessity of Aruco markers which take lots of space (I don't have enough space between the 2 counters to have 2 sets of markers and be able to crop a zone with only 2 markers around each counter).
Would you consider to make the use of Aruco markers optional?
You will find here attached the original photo and the cropped photo around the second counter.
![meter](https://user-images.githubusercontent.com/2734930/171938497-26e2050e-9d03-41cf-a4f6-40afeeec02d3.jpg)
![meter-cropped](https://user-images.githubusercontent.com/2734930/171938552-58a40eb7-b5fd-472e-a7ae-ceebad9368ed.jpg)
.

**Comment by junalmeida** [comment]
I can't make the use of markers optional, otherwise I couldn't make it easy enough for users to select a region of interest. Without it, the whole image would be considered and then impossible to get each meter at once. 

What I could do is to add a parameter to specify the Aruco Marker number to search for. Each Aruco marker corresponds to a number. Currently the addon accepts any if you at least choose two numbers in ordinal order.

If I add the parameter to force a specific Aruco marker, then you could have a second set.  

It seems to me that something is wrong, because in your image you have set the pair around the first counter, and it selected the second. I can't figure out why this is happening to you. The way it is supposed to work is to crop between the lower-right of the first marker and the top-left of the second marker.

If I add the parameter to force a specific marker, then it won't matter if your markers overlap, for eg:

![image](https://user-images.githubusercontent.com/991675/171954268-b37cae8d-08ce-42cc-a7db-fd7db428df1e.png)

**Comment by Sheugel** [comment]
Thanks for your reply.

That would be great if you do like you suggest: add a parameter to specify the Aruco Marker number to search for.

Thanks!

(about the cropped image of the counter, it was just to illustrate that you can have a virtual camera with the "Camera Proxy" integration [https://www.home-assistant.io/integrations/proxy] of a specific region interest (the original camera image is cropped), making the use of Aruco markers useless)

**Comment by junalmeida** [comment]
Ah I see. That makes sense. However, this solution is not good for all users. For eg my meters are outdoors, subject to wind blows that could shake and shift a camera some pixels around. The Aruco markers is to solve that minor movements.

Once I have a spare time I will add the parameter to force aruco markers.

**Comment by Sheugel** [comment]
Thanks!
You're right. It's more convenient with the markers even indoor, if for some reason, you need to handle the camera or smartphone or the tripod gets bumped into... And with two counters, even more so.
By the way, you should advertise your addon on the Home Assitant community!
And I'm sure that it being able to handle day and night counters can be an added value. I think it's quite common in Northern Europe.

**Comment by junalmeida** [comment]
@Sheugel thanks for your suggestion, I will definitely make an announcement on the forums once I have some time  to write a good post.
Stay tuned for the next version :)
